### ISSUE TITLE
Compatible w/ Illustrator v. 22.0.1?

### ISSUE THREAD

**Issue by AlainParadis** [Silly-V/Adobe-Illustrator#11]

**Comment by Silly-V** [comment]
Sure, what's wrong with it?

**Comment by AlainParadis** [comment]
One of my faculty is in class right now and it's not loading for them. He says:

"That one gives you an error as soon as you open it. Won't even load the script dialog."

This is tough, because I'm not with him. I'm going to try it myself now.

**Comment by Silly-V** [comment]
Sounds like the issue one would have due to incorrect download method. Make sure that they are indeed using the raw script page and doing a save as.

**Comment by Silly-V** [comment]
However, if they were able to run it first and saved a settings file and then it does this, it may be related to Slavi's issue: on the Mac for him the settings file ends up having no content for some reason.

**Comment by AlainParadis** [comment]
Yup. I just loaded it and it worked. Thanks for getting back to me so quickly. I'll tell him.

**Comment by Silly-V** [comment]
I hope it is going to end up working for him, and yes I'm here (so long as I live) to support the workflow and aid any users who have issues! Also thanks for making this a part of your training course, it is so much appreciated!

**Comment by MJholland** [comment]
Hello, I'm part of the course doing this and we are getting the following error. This was after downloading the current code from here.
![screen shot 2017-11-23 at 2 29 36 pm](https://user-images.githubusercontent.com/16650658/33186838-df6f68b6-d05a-11e7-8e6e-b163100cd182.png)

**Comment by Silly-V** [comment]
Please make sure to go to the "Raw" button and click Save As, then save as a .jsx file- which is a text file. When you have gone to the Raw page and saved the file, if you open it up in Notepad there should be no <to></td> HTML tags or any kind. Please try this and let me know your result .
