### ISSUE TITLE
vertical text

### ISSUE THREAD

**Issue by Rynkeegan** [Silly-V/Adobe-Illustrator#12]
when i run the variable importer script and link database, all my vartical text gets changed to horizontal? Can you use variableimporter and apply to vertcal text? Please help?

**Comment by Silly-V** [comment]
What version of Illustrator do you use?
I was able to bind both a vertical point-type text as well as vertical area-type text, using CC2018 (v22.0.1). Please see screenshot. 
![2017-12-01 12_11_02-com adobe adobesplashkit textwindowclass](https://user-images.githubusercontent.com/11342704/33496788-2fdbe702-d691-11e7-84f5-1fe4e3daa09e.png)

**Comment by Rynkeegan** [comment]
2017 1.0 cc  -  I used a work around and just typed # then enter then # then Enter. And got the results I need. I just could not get it to work with vertical text tool but I will try again

 

THANK YOU SO MUCH FOR YOUR RESPONSE.

 

First time and did not know if anyone was out there.

 

THANKS

 

Ryan Keegan,        Art/Digital

Rockford Silkscreen Process, Inc.

ryan.keegan@rockfordsilkcreen.com

**Comment by Silly-V** [comment]
Maybe you were using carriage returns to create the vertical text inside the data file?

**Comment by Rynkeegan** [comment]
Oh wait, the text has to be vertical in the Excell file?

**Comment by Silly-V** [comment]
No, I was just wondering if that was what you were doing initially. Well, maybe it was some issue regarding vertical text in cc2017? In any case, I will ask you for your sample file so I can see the issue better via email. Thanks!

**Comment by Rynkeegan** [comment]
It worked changing my excel file to vertical text then importing

**Comment by Rynkeegan** [comment]
Another question if you don’t mind?

 

When using the Variableimpoter is there a way to have the fonts outlined as it saves the records out of the batch? So that the individual EPS files have outlined fonts?
