### ISSUE TITLE
Variable name XML Syntax problem

### ISSUE THREAD

**Issue by Rus57** [Silly-V/Adobe-Illustrator#15]
Hi,
I'm new at trying out the script on a 22.01 Illustrator version and after many experiments I'm now stuck.
I keep getting this message:

Proper XML Syntax isn't followed by some variable name(s)
1) Element names are case-sensitive
2) Element names must start with a letter or underscore
3) Element names cannot start with the letters xml (or XML, or Xml, etc)
4) Element names can contain letters, digits, hyphens, underscores, and periods
5) Element names cannot contain spaces
(All names are going to be Auto-replaced):
--------------------------------------
image-001;image-tag-001;comment-001;comment-tag-001;@image-002;image-tag-002;comment-002;comment-tag-002;@image-003;image-tag-003;comment-003;comment-tag-003

Fact is, all variable names seem to be OK and it's still not working.
What am I overlooking?
Thanks for any tips!

**Comment by Silly-V** [comment]
Can you send the data file to me at Vasily.hall@gmail.com ?

**Comment by Rus57** [comment]
Just sent it

**Comment by Rus57** [comment]
Somewhere in the comments below the YouTube video about Illustrator and your script from John Garrett was someone with exactly the same issue. Posted 9 months ago. But there was no reply.

**Comment by Silly-V** [comment]
Hi, the issue is the CSV file format. At this time, Variable Importer does not support semi-colon (;) delimitation. Please save with comma-delimitation (,) and try it this way.

**Comment by Rus57** [comment]
Thanks, that must be about the only thing I didn't try ;-(
But good to know. I'll change this.
It seems like you wrote a very nice piece of code!

**Comment by Silly-V** [comment]
Thanks, it took about 1 year of writing it from a very simple snippet that
took string data apart with splitting it by commas.. then after the version
7 was out, it was time to re-do the entire thing with a better interface.
Now it's mostly working for everybody except CS4-down there's some strange
issues.
I hope it worked for you. If it did, can you please close the issue?
Thank you,
-Vasily

**Comment by Rus57** [comment]
If I run into something I'll let you know. I'm still trying to figure out how to make this CSV in an easy way really comma separated, when exporting from Excel. When I have solved this and checked everything I'll close it.

**Comment by Silly-V** [comment]
I think there's just some export option ?

**Comment by Rus57** [comment]
It's rather hidden,but this was the best guide I could find: https://www.itsupportguides.com/knowledge-base/office-2013/excel-20132016-how-to-change-csv-delimiter-character/

**Comment by Rus57** [comment]
What happens when the text contains comma's? ( I did not check this yet ...)  Would I need to enclose all text with these quote characters?

**Comment by Silly-V** [comment]
I believe Excel does this automatically, which is driven by that delimiter
setting.

**Comment by Rus57** [comment]
No, sorry to say, but it's not that easy. I changed the setting and Excel is now back to semi-colon's. Also Excel does not ad quote signs when exporting to CSV-UDF8 format. Except when I put the text within quotes myself. The it ends double quotes (!) at the beginning and the end, so i end up with text that is embeded in threefold quotes. I have to stop now. Will go on later. Getting a CSV export from Excell in an the right CSV format turn out to be a small nightmare :-(

**Comment by Silly-V** [comment]
Say, what Excel version are you on ?

**Comment by Rus57** [comment]
2016. That's the latest I got so far from my Office 365 subscription.

**Comment by Silly-V** [comment]
Hmmm so you say when you changed the list separator into commas, it didn't
close off the commas via quotes when you saved as csv ? I would expect a
list separator setting to drive the same behavior as far as setting quotes
goes. Ill of course look at it later when I get home.

**Comment by Rus57** [comment]
No, that's what I found. But even weirder: now the list separator in Windows is a real comma, but in the Excel export it witched back to a semi colon. Will continue this later. Hope you find something.

**Comment by Silly-V** [comment]
Okay, after some further analysis, it became clear that semicolon-delimited .csv formats are indeed common and therefore it would suit everyone best that this feature gap would be addressed. Especially as the code edit needed for the new handling is quite minimal, I brought in the automatic detection and parsing of a semicolon-formatted CSV. Thanks to Andy VanWaggoner's CSV code which takes in a splitter as a parameter, I was able to test the first row of the text file for the condition of having semicolons and not having commas and then set this splitter to a ";" semicolon character. Now it should satisfy the needs of those whose regional language settings cause Excel to export the semicolon formatted .csv files!

**Comment by Rus57** [comment]
Thanks! I uploaded the new script and this did a seamless import of the CSV file (UDF8) I exported from Excel. I'll continue with my experiment ;-)
