### ISSUE TITLE
"Export As..." overwrites existing file

### ISSUE THREAD

**Issue by maedi** [Silly-V/Adobe-Illustrator#16]
When using a batch action to "Export As...", the "Dataset Names" aren't appended to the filenames. This results in the same file being overwritten again and again.

Using "Save a Copy..." batch action works as expected. I need to export as bitmap though.

Illustrator CC 2018 and Variable Importer 8.1.10

**Comment by Silly-V** [comment]
First and foremost, please ensure the Override Export commands checkbox is on.
If that's already properly checked and the issue persists, here's a small test which may or may not help.
When recording the Export action, try to either do the export with the default name that Illustrator provides, or the reverse of that which is to type in your own custom name for the file. See if this has any effect on what the export.

**Comment by Silly-V** [comment]
I tested this out and possibly re-created your situation. I did not pause and began right away, 'exporting' my document. However I had the "Override Save-As" checkbox on and not the Export one. Checking the Override Export checkbox did the trick, but not without a small yet preventable nuisance: note that these checkboxes each hold a different destination path which is remembered from the last time you used this option in Illustrator. Not having properly configured this, I found myself having exported files into some directory I've not used in years.

**Comment by maedi** [comment]
It was selecting 'Override Action "Export" Commands', thank you.

I tried creating a batch action with the default filename and with a custom filename. You may be interested to know that modifying the default filename makes the batch action add the file extension.

**Comment by Silly-V** [comment]
Aha! Yes this turns out to be one of those Illustrator gotchas. Thanks for verifying and elucidating the solution for this issue.
