### ISSUE TITLE
Script Alert: Data import defaulted to generic dataset names

### ISSUE THREAD

**Issue by eguiadaniel** [Silly-V/Adobe-Illustrator#19]
![dataset 3](https://user-images.githubusercontent.com/40235952/41349259-9ecb1658-6f0f-11e8-88ee-d5e553aff12e.PNG)

Ive got this error that turns all the dataset names in Record1, Record2, Record3... Somehow is related to the number of rows in my CSV file. Ive tried with 400, 200, and 150 rows and all them get this alert. With 120 rows i´ve had no problems and all my dataset names where displayed correctly.

Is there anyway i can fix this issue?
Thanks in advnace and congratulations for such an usefull script!

![dataset 4](https://user-images.githubusercontent.com/40235952/41349427-2473e852-6f10-11e8-90ed-ce3c3752d453.png)

**Comment by Silly-V** [comment]
It looks like it's also defaulting your variable names. In one of your data cells must be an item which does not conform to the XML syntax and causes genericizing of the data. Are you using some data in the rows between 120 and 150 which could have such an issue?

**Comment by Silly-V** [comment]
This issue will be scheduled to be closed in 19 days without user input.

**Comment by Silly-V** [comment]
Issue will be closed; no sample file was supplied :(
