### ISSUE TITLE
Dialog does not change when selecting Options, File Paths, etc

### ISSUE THREAD

**Issue by PaulShadwell** [Silly-V/Adobe-Illustrator#2]
When I import a CSV the window does not update with Variable names until I click Transpose Data, then a message appears and when I uncheck Transpose Data the wind is correct.
Selecting Options, File Paths, Presets or Test does nothing.
Import Variables works but I cannot set any options.
Illustrator 2015.2.1 Release 19.2.1.

**Comment by Silly-V** [comment]
Can you send me any screenshots and the .csv file to my email please? vasily.hall@gmail.com

**Comment by Silly-V** [comment]
I could not reproduce this issue on my systems, but after a series of rudimentary testing edits, the issue also disappeared for unknown reasons on @PaulShadwell 's machine.
