### ISSUE TITLE
Data Set Name Resetting on Load New Variable Library

### ISSUE THREAD

**Issue by kimjavvi** [Silly-V/Adobe-Illustrator#20]
I just used your script and has worked wonders in my tasks. But as I was working on it yesterday I stumbled upon an issue. Whenever I upload a new variable library the dataset names will be set to default "Data Set 1" and so on. The first time I imported the script, I clearly remembered that I already set the format for the dataset names that I need but when I load a new library? It resets. 

Is there a way to solve this issue? Am I missing a procedure or something? Your response on this would be of great help. Thanks in advance. 

![dataset-names](https://user-images.githubusercontent.com/25051175/42617585-be43afea-85e4-11e8-8d09-af6841dc2794.png)

**Comment by Silly-V** [comment]
Hi, when it makes all dataset names generic, it means there is a record or variable name which may have xml-invalid characters in it. Ensure the variable names you use contain no spaces , etc. If you send me the CSV sheet, I could probably determine which record causes the issue.

**Comment by kimjavvi** [comment]
I did replace the variable library without using the script since my template was saved on the adobe libraries and I just want to easy import a new library. Will the dataset name format that I declared initially will reset in this case? Now, I have to copy and paste again the dataset names to each dataset which takes up a lot of time. Looking forward for your response. Thanks!

**Comment by kimjavvi** [comment]
This is good though, but in this case whenever I do the reimporting of new data sheet through the script, it resets the assigned text frames to the variables so I have to click each text frame and their corresponding variable then click "Make Text Dynamic" again. In this case, the dataset names are fixed but the re-assigning of variable again happens. Can I just import a new variable library (datasheet) then retain the variables assigned and the dataset name format at the same time? This could be a good additional feature to your useful script.

**Comment by Silly-V** [comment]
Yea you use the auto binding options. These options allow you to automatically re bind all variables by the name of the art in the layers, or the notes on that art's attributes notes. Using a preset captures your auto bind settings, although it is set this way by default anyway. 
To use the binding by name option, make sure your art in the layers panel corresponds to your variable names in your spreadsheet.

**Comment by kimjavvi** [comment]
By "art in the layers panel"  you mean I should rename my layers (the text frames) to the names of the variables? and should be of the same order too?

**Comment by kimjavvi** [comment]
Not yet, got caught up by work. I'll probably try this anytime this week and I'll get back to you soon. 
Thanks!

**Comment by kimjavvi** [comment]
Hi Silly-V,

Tried your suggestion and it worked! Thank you for attending with me on this issue. 
Wishing you for more successful works like this. 

Thank you.
