### ISSUE TITLE
Json data

### ISSUE THREAD

**Issue by impactcolor** [Silly-V/Adobe-Illustrator#22]
Is there anyway it can be set to import json data instead of csv or xml?

**Comment by Silly-V** [comment]
Perhaps one day when a pro-level extension is released there will be a JSON option with ability to perhaps add in your own converter snippet to ingest any kind of custom JSON format.
Meanwhile, have you looked into any online tools to accomplish part of the steps such as a JSON-CSV converter? http://www.convertcsv.com/json-to-csv.htm

**Comment by Silly-V** [comment]
I encourage anyone who has JSON needs to send their format preferences, use cases and opinions to my email address: vasily.hall@gmail.com
