### ISSUE TITLE
Need illustrator open .ait  script

### ISSUE THREAD

**Issue by sgops27** [Silly-V/Adobe-Illustrator#23]
I have created some illustrator template files (.ait) placed in my local D drive (path), 
Ex: 00_Helvetica_27 x 40, 00_Helvetica_28 x 47 (and Many)

once I run the script open that popup template file (attached i create the screenshot) window and select what file i need then hit OK open that file.

it's passable in javascript
![WhatsApp Image 2019-02-28 at 9 57 11 AM](https://user-images.githubusercontent.com/47688301/54736729-9108d000-4bd2-11e9-9f43-941dec2c854f.jpeg)
?

**Comment by Silly-V** [comment]
The native variables feature that the VI script uses does not possess an ability to do any work on .ait templates.
If you first wish to open a template and immediately run the Variable Importer script thereafter, you could just use an action and record two script-menu-items to run consecutively. Although I have not yet tested this.

**Comment by sgops27** [comment]
Actually, my team is more than 15 peoples, so we need quality and consistency fonts and font size, many things, i have fixed all in our template files (.ait). that files placed in server path Ex:\\172.24.161.52\books\Template (already we have used the 
script attached here but that script decoded) my old server some space problem, (we need more sapce) so they are allocated the new server in my team, now that script is not working we unable to change server path that script it's decoded so pls help me.
[Template.zip](https://github.com/Silly-V/Adobe-Illustrator/files/2994839/Template.zip)

**Comment by yorksk** [comment]
I'm not sure about server. My script for local drive. Read comments inside of script.
[MyTemplates.zip](https://github.com/Silly-V/Adobe-Illustrator/files/3052707/MyTemplates.zip)

**Comment by sgops27** [comment]
Hooo it working fine, amazing work thank you so much
[image: image.png]
