### ISSUE TITLE
Add a function to import colors

### ISSUE THREAD

**Issue by hermify** [Silly-V/Adobe-Illustrator#27]
Hi there,
as i saw in your other script, there is a possibility to import colors to illustrator to fill in.

Would it be possible to simply add this functionality inside this importer-script?

Thank you

**Comment by Silly-V** [comment]
Sorry but importing colors is only possible with external additional processes which must happen after data import and during dataset export, or processing.
You may already have used the links in this answer: https://graphicdesign.stackexchange.com/questions/106452/fill-color-hex-value-as-variable-to-be-used-in-data-set
It may be possible to achieve your goals with the help of a more powerful data-to-art utility, I am personally hoping to create one during the next few years. We shall see how it goes.
