### ISSUE TITLE
Can't set variable as data set name

### ISSUE THREAD

**Issue by niyamax** [Silly-V/Adobe-Illustrator#30]
Variables are not shown while assigning value to data set.

**Comment by Silly-V** [comment]
You must first ensure you have a selected CSV file in the dialog before being able to set a dataset name field to a variable's value. Does this attached image help?
![image](https://user-images.githubusercontent.com/11342704/70839750-de1d7980-1dd3-11ea-8427-8b019bf017f8.png)

**Comment by Silly-V** [comment]
Any feedback or news regarding this issue?

**Comment by Silly-V** [comment]
Come back and re-open if this did not solve your issue.
