### ISSUE TITLE
error loading on Illustrator 2020

### ISSUE THREAD

**Issue by malavante** [Silly-V/Adobe-Illustrator#31]
I used this script in the past but with latest update don't work.

Error 60: Not Well formed (invalid token)
Line: 499

What should I do please?

![Variable Importer issue](https://user-images.githubusercontent.com/59850693/72298391-1ef9fe00-36b2-11ea-881e-53d937bfd8d8.JPG)

**Comment by Silly-V** [comment]
Use the "Raw" button and copy or download the text, do not save the github website.
