### ISSUE TITLE
Error 23: & does not have a value. Line 143

### ISSUE THREAD

**Issue by mdmarein** [Silly-V/Adobe-Illustrator#32]
Hi Silly-V,
Im using Adobe illustrator v24.0
When a try to use the script i have de following screen error

Error 23: & does not have a value. Line 143
<img width="501" alt="Screen Shot 2020-01-23 at 16 39 43" src="https://user-images.githubusercontent.com/60237441/73019255-ff757a80-3e01-11ea-9353-a30e7b17873f.png">

**Comment by Silly-V** [comment]
Go to https://github.com/Silly-V/Adobe-Illustrator/blob/master/Variable%20Importer/VariableImporter.jsx

And use the Raw button to copy or download the text.

![image](https://user-images.githubusercontent.com/11342704/73143970-c9d0cb80-4065-11ea-98c1-7eb26b5cad04.png)
