### ISSUE TITLE
Variable Importer is not working on Illustrator 2019 neither 2020 CC

### ISSUE THREAD

**Issue by malavante** [Silly-V/Adobe-Illustrator#33]
is simply stops working on recent updates. 
Show errors a show on attachements
I tried the 2 files on repository

VariableImporter.jsx    ![variable error](https://user-images.githubusercontent.com/59850693/74386784-fb5ddb00-4e4a-11ea-96b4-c0976cebb176.JPG)

Legacy-VariableImporter_v7.1.3.jsx      ![Legacy variable error](https://user-images.githubusercontent.com/59850693/74386802-07e23380-4e4b-11ea-8b8f-1efb9d6a7ce4.JPG)

**Comment by Silly-V** [comment]
Don’t download the whole website. Use the raw button and only download the text. 

The raw button says “Raw”.
