### ISSUE TITLE
VariableImporter - Linked Images being added to wrong layer (out of place and all to the same layer)

### ISSUE THREAD

**Issue by masonspacestation** [Silly-V/Adobe-Illustrator#37]
Hello Vasily, I hope you are well.
Variable Importer has been my backbone for about a year and a half now - what an amazing script!
I have an issue right now that I've never seen before, and I'm hoping you will have some insight into what may be happening. I've recorded a Loom video to show it a little more easily than writing a description, but here is the summary:
When I import multiple datasets, all linked images are placed in the bottom-most layer that has a variable element inside it, rather than where they are assigned prior to import. They are also placed aligned to each other off of any artboards, just out in space.

I hope that you will have a few minutes to see my video and see if it looks familiar to you.
If you'd like me to provide my Excel and Illustrator files, I can do that.

Thank you!
Andrew Mason

Loom Video:
https://www.loom.com/share/7e1beb1e1c894706b40749d0930be37b

**Comment by Silly-V** [comment]
Hi Andrew, this looks like something I've never ever seen before.
Can I get a sample file which does this, so I can try to reproduce on my end?

**Comment by Silly-V** [comment]
This very obscure issue has been solved! Apparently Illustrator acts strangely when visibility variables are used and some of the variable images are inside a visibility group while others are outside. It appears that in some cases, the image object outside of a visibility group will attract the image objects from those groups and pull them in next to it at full size and out of place.

Thanks, Andrew:

> After writing this last night, I had a eureka moment, and it seems like I’ve found the issue. It’s a mistake on my part, of course. I’ve recorded a short video to explain, but basically, all my variable elements were grouped together in 4 groups for the different layouts, and toggled by the visibility feature (X in the column of the group name). I thought I was streamlining this by keeping the QR codes (which don’t move with the layout changes) in a static layer.
>  
> https://www.loom.com/share/8386bd462fc34affa675e1ef38550a04
>  
> For some reason, those QR codes pull all the linked images into their layer instead of the assigned groups.
>  
> I deleted the QR codes from the static layer, and added them to each variable group, and it’s working like a charm again, just the way you intended!
