### ISSUE TITLE
Proper XML Syntax isn't followed by some variable name

### ISSUE THREAD

**Issue by Huaba93** [Silly-V/Adobe-Illustrator#39]
When I try to import my variable file I get this error:
![image](https://user-images.githubusercontent.com/21239003/96575802-86904a00-12d1-11eb-9896-f826bf3207e9.png)

My variable names should be fine. When i split my file into multiple ones, it works. I have no idea what is causing the problem. I can't reproduce the problem with my large sample file. See attachment. 

Working:

- LargeSample 
- Varibables_de_en_es_fr_it
- Varibables_ja_ko_pl_pt_ru

Not Working:

- Varibables_de_en_es_fr_it_ja_ko_pl_pt_ru

[SampleFiles.zip](https://github.com/Silly-V/Adobe-Illustrator/files/5408127/SampleFiles.zip)

**Comment by Silly-V** [comment]
There is a blank column in your file which is not working.
