### ISSUE TITLE
Artbinding

### ISSUE THREAD

**Issue by Guero67** [Silly-V/Adobe-Illustrator#4]
Greetings
Being a novice to Adobe Illustrator and GitHub, I hope someone can help me out.
I used the Adobe-Illustrator/Variable Importer/VariableImporter.jsx file about two weeks ago once and it worked great!

I had to reinstall Adobe Illustrator today CC on Windows 10 and download the VariableImporter file on my computer.

After many hours my objects are still not being recognized by the script.  I’ve installed and uninstalled both Illustrator and the script. Any ideas will be greatly appreciated.
Thank you!

My Illustrator file has three objects: product, state, and image (it’s a linked image file)
![adobe illustartor cc on windows 10](https://cloud.githubusercontent.com/assets/21075282/17839224/6b5711c8-6796-11e6-878f-028d8e606f7b.png)

My CSV file has the following header columns: product, state, and @image 

My variables are: product, state and image and are recognized at the import stage.
![use headers recognized](https://cloud.githubusercontent.com/assets/21075282/17839217/375b7d5a-6796-11e6-933e-9b63ec59e1c0.png)

Options and Binding by Name Set
![options and binding by name set](https://cloud.githubusercontent.com/assets/21075282/17839230/a3b0f32c-6796-11e6-8a87-ecd03b7e176c.png)

Prepended Image Path
![prepended image path](https://cloud.githubusercontent.com/assets/21075282/17839234/c0f36fbe-6796-11e6-9461-51026c7197a6.png)

Ran the Tests
Dataset Names found (32) Good
Image Files found (32) Good
Graph files N/A

Test Artbindings Not Found
![test artbindings not found](https://cloud.githubusercontent.com/assets/21075282/17839240/07765960-6797-11e6-8f6e-83c5176ef79b.png)

After import, Illustrator recognizes datasets and variables but not objects
![dataset recognized but illustrator objects are not](https://cloud.githubusercontent.com/assets/21075282/17839245/1a89b682-6797-11e6-98fd-0c4be35c1e39.png)

**Comment by Silly-V** [comment]
See how there's a triangle next to your "image" art? That means it's not a real image. You should replace whatever art that is, with a linked image.
Also, make sure your text in the text that gets the changed text is not named the same as your variable name for that text. In other words, always make sure that your starting point placeholders never say "product" or "state", if your variable names are also "product" and "state". Those are not names but text previews. Change the text contents and watch the name in the layers change too - this means it is not named.

**Comment by Guero67** [comment]
Good evening-

Thank you for your prompt response.

I got it to work in three minutes!

I just have to remember while objects and variables need to have the same
names to auto-bind but if I have a text object, I have to click select and
add different text afterwards to the text object.

Your scripts the best.

Thanks!

Mateo
