### ISSUE TITLE
[Question] Line breaks

### ISSUE THREAD

**Issue by Huaba93** [Silly-V/Adobe-Illustrator#42]
Hi. Is it possible to force line break in area type text? If yes, what I have to do? Could you provide me with a sample?

According to this documentation it should work...but I can't get it to work.
https://prepression.blogspot.com/2015/04/illustrator-variableimporter-script-tutorial-5.html

**Comment by Silly-V** [comment]
You can either have line-breaks embedded in your CSV text by using a spreadsheet editor's features which allow to enter line-breaks. Usually it's Shift+Enter or Alt+Shift+Enter. And you can simply paste text into your spreadsheet editor from other sources which already contain line-breaks. Note that if you are using some latest versions of Excel and see only one line of text in the cells where you expect there to be more than one line, it's some Excel quirk going on whereby it combines all lines into one within the cells. However in such a case if you click on the editing bar and then click away, you can observe the excel cell expand into the proper line-breaks, heightening the cell.

Also you can turn on the VariableImporter line-break feature which converts all found instances of `\\` double backslash into line-breaks. To do so you check that option in the Options tab, Settings 'area'.

**Comment by Huaba93** [comment]
Ok it seems to be I had problems with excel...the double \\ feature works as expected. Thank you very much for you help. This tool is awesome. We Use it for our appstore presence. With the next update in a few days we will generate over 5000 images. This would not be possible without this tool.

A big thanks!
