### ISSUE TITLE
compatibility with Illustrator 2021

### ISSUE THREAD

**Issue by hoochalaffa** [Silly-V/Adobe-Illustrator#46]
Hello!

I am a big fan of the variable importer script. There seem to be issues running in the latest version of illustrator 2021 as well as the x.01 version. When I installed 2020 and ran it, it worked as expected.

symptoms are that illustrator crashes when the script is open. It takes a few seconds, and happens for me when switching to the testing panel before import.

**Comment by Silly-V** [comment]
You issue may be related to this bug, which Adobe claims is now fixed. Is it?
https://illustrator.uservoice.com/forums/601447-illustrator-desktop-bugs/suggestions/41739235-illustrator-2021-version-25-0-0-crashing-when-ru

**Comment by hoochalaffa** [comment]
I had to downgrade to x.01 for a different plugin that wasn’t working on x.1. Let me see if upgrading it again works for variable importer.

**Comment by hoochalaffa** [comment]
Yes, it works properly in 25.1. Thanks for pointing me in the right direction.
