### ISSUE TITLE
Data source files greyed out, can't select

### ISSUE THREAD

**Issue by aarontheman** [Silly-V/Adobe-Illustrator#48]
Used the script successfully a couple weeks ago. Now, none of my data source CSV files are recognized by the script as openable -- all are greyed out. The 'Sample Data 1.csv' file does work for some reason.

**Comment by aarontheman** [comment]
Ah, it's because the files are on the Dropbox cloud. They must be interpreted as read-only or something? Maybe you can clarify. Moving the files onto the local drive fixed it.

**Comment by Silly-V** [comment]
That's good to know, I don't know much about that. Thanks for providing the answer! I will add it to documentation when that gets out.
