### ISSUE TITLE
Illustrator Version 25 on Mac OS Big Sur. 

### ISSUE THREAD

**Issue by Tylersprice96** [Silly-V/Adobe-Illustrator#50]
This script is essentially non-functional within Illustrator Version 25. At least on Mac OS Big Sur (11.2.3). Absolutely loved using this in older version of Illustrator. Just wondering if this script is still being kept up to date. If so I would be very interested in helping troubleshoot and resolve the issues to get a version working in the aforementioned environment. Is there somewhere I can send Illustrator crash reports? Thanks for your incredible work on this script, look forward to hearing from you.

**Comment by Silly-V** [comment]
They fixed something on version 25, so it's supposed to be working in 25.1 or 25.2 -  can you confirm your sub-version (after the 25. bit) ?

**Comment by Tylersprice96** [comment]
Ah I see, yeah I am running version 25.0. (Sorry should have clarified that) Unfortunately it doesn't look like the 25.1 or 25.2 update is live for those of us using Mac OS. I guess I will just hang tight until I see the next update come around and then I will keep you posted. Thanks for the super fast response!

**Comment by Silly-V** [comment]
Oh I see, and sorry to hear that you are going through such a situation. Unfortunately, I was not able to determine the cause of the issue as anything that I could do anything about as it has the problem just in that version and once they fixed it, it just went back to working as normal.
I guess Big Sur is so new that it's not caught up yet with Illustrator versions? Maybe I will get my new mac laptop soon and see what's happening there.
