### ISSUE TITLE
[VariableImporter.jsx] Not able to do the binding

### ISSUE THREAD

**Issue by psjavi** [Silly-V/Adobe-Illustrator#56]
Hi, I'm trying to bind a csv in order to create in batch the email signature

![image](https://user-images.githubusercontent.com/4563033/155735994-ce8a49c5-ec92-40da-af3e-0f45e12fe125.png)

When I try to do the cycle process, nothing happens. If I push in OK, the records are created but the text in the variables it doesn't change.

What I doing wrong?

I've the latest Illutraitor version.

**Comment by Silly-V** [comment]
Make sure the text is different from the text box name. Type something into the textbox. If the name of the text box in the layers panel changed, it means this textbox has no name. Change the text inside the textbox to a different string of text, and then rename the textbox in the layers panel to give it a proper name. Now it could be recognized by autobinding when using bind by name.

**Comment by psjavi** [comment]
> Make sure the text is different from the text box name. Type something into the textbox. If the name of the text box in the layers panel changed, it means this textbox has no name. Change the text inside the textbox to a different string of text, and then rename the textbox in the layers panel to give it a proper name. Now it could be recognized by autobinding when using bind by name.

Good morning, It worked!. Thanks a lot!!
