### ISSUE TITLE
File name doesn't change with export to PNG

### ISSUE THREAD

**Issue by pokerjk** [Silly-V/Adobe-Illustrator#58]
Hi,

When trying to export the data set to PNG, the file names don't change even though I have it set to change to the data set name.

It works when saving a PDF but not PNG.

Anyway to make it work?

Thanks,
J

**Comment by hoochalaffa** [comment]
In the action you’re using for png, does it say export or save? When setting up the batch action, the options have two checkboxes, one for export and one for save as.

I had a similar issue exporting eps files and it was that I had save as and export checked in the batch action options. I had to have either export or save selected and that had to match up to what was in the action.

**Comment by pokerjk** [comment]
Ah, awesome.

Thanks so much @hoochalaffa
