### ISSUE TITLE
Error importing script (VariableImporter.jsx)

### ISSUE THREAD

**Issue by pjanusc85** [Silly-V/Adobe-Illustrator#6]
Adobe Illustrator 2015.3.1 Release
20.1.0

Error Message:
Error 60: Not well-formed (invalid token).
Line 631:
-> </span></td>

**Comment by Silly-V** [comment]
XML-related error.
Can you send your csv file to my email at vasily.hall@gmail.com ?

**Comment by u2junk** [comment]
Sorry,
I think you replied to the wrong email address. I don't remember having a XML-related error.

Sent from Yahoo Mail on Android 
 
  On Mon, Oct 24, 2016 at 9:26 PM, Silly-V<notifications@github.com> wrote:   
XML-related error.
Can you send your csv file to my email at vasily.hall@gmail.com ?

**Comment by Silly-V** [comment]
I didn't reply to any email address, I post comments back on the github Issue.
So for some reason you're subscribed to this thread - maybe try to unsubscribe.

**Comment by hsawires** [comment]
The error occurred before importing and CSV 
after restarting Illustrator
File > scripts > VariableImporter
then the error
```
Error 60: Not well-formed (invalid token).
Line 631:
->
```

**Comment by Silly-V** [comment]
So, it's actually when you try to run the script at all? Well, let me ask - which method do you use to download the script to your machines? You may not be getting a correct format if you don't go to the Raw tab to save the entire contents as ".jsx" format.

**Comment by Silly-V** [comment]
> 1. Went to website: https://github.com/Silly-V/Adobe-Illustrator/tree/master/Variable%20Importer
> 2. Downloaded file by right clicking and clicking save as: Variableimporter.jsx
> 

This is incorrect: after you go to this website, do not stop there - you have to go to the Raw button to view the raw text. Only then, use Save As to save the raw text as .jsx. When you click Save As on the web page, you are saving the entire github webpage as HTML which is the cause of your error.
