### ISSUE TITLE
Crash in CC2017

### ISSUE THREAD

**Issue by provides86** [Silly-V/Adobe-Illustrator#7]
Illustrator CC2017 for mac crashes when importing variables

**Comment by Silly-V** [comment]
This is very true, something is definitely not working well in CC 2017. Do not use until fixed.

**Comment by Silly-V** [comment]
Script is edited, should be working again now. Get the newest version and try a test.

**Comment by provides86** [comment]
Thank you for the quick replay, but I´m sorry to say that Istill having issues with illustrator crashing

**Comment by Silly-V** [comment]
I see! There was one little change I needed to make, please try it now!

**Comment by provides86** [comment]
Perfect!
