### ISSUE TITLE
Multiple Artboards

### ISSUE THREAD

**Issue by realmofadam** [Silly-V/Adobe-Illustrator#8]
My AI template contains multiple artboards with multiple objects with the same names (see screenshot for more clarity). My hope was to use the script to import variables and have them apply to all of the instances of the objects. If this is not possible, might there be a workaround that is not occurring to me? 

Thank you for all of your hard work with this script! I'm hoping I can get it to apply to my situation.

Adam
![screen shot 2017-07-16 at 6 32 59 am](https://user-images.githubusercontent.com/17643600/28246811-a2f3871c-69f0-11e7-8a38-169a658331eb.jpg)

**Comment by Silly-V** [comment]
Yea you just do it, what's stopping you?

**Comment by Silly-V** [comment]
Oh, I know! Make sure your placeholder text does not say the name of your variables. This is a very common problem: your names you see in layers panel are not really names. They are previewing your text. Only if your text box text is different, can you "really" name your text box. Yes , I know this sounds about as reasonable as it does, but once you've learned this little gotcha, you're good to go.

**Comment by realmofadam** [comment]
Awesome. Thank you for your help. Again, great work!
