### ISSUE TITLE
2017.1 Illustrator Breaks Variable Importer

### ISSUE THREAD

**Issue by sfdesigner** [Silly-V/Adobe-Illustrator#9]
Greetings -- It seems that the new update to Illustrator breaks Variable Importer. Now when I import and cycle through the CSV data import, it doesn't bring in any data.

**Comment by Silly-V** [comment]
It still works just fine for me, are you sure you have labelled your art correctly, etc?

**Comment by sfdesigner** [comment]
Yeah. I am working with a template that has worked fine for the last several months, but with the latest update that I installed this week, it no longer works.

D.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Silly-V** [comment]
Hmm are you on a pre-release program? Is the version you installed a different number than "21.1.0" ?

**Comment by sfdesigner** [comment]
I think I figured it out. It wasn't the latest version of your jsx file. I had 8.1.3 installed. I updated and things are fine now.

BTW. Your script is a lifesaver. I love it. I am at LinkedIn and use it for processing graphics for Lynda.com and LinkedIn Leaning. Also, FYI, I used to be an Adobe product manager, so I'm excited to see such an awesome community project like this. Great job!

DougW

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Silly-V** [comment]
Well glad to be of service. You know, I am thankful for Adobe's half-baked VDP feature, it has helped me get my freelancing into some large organizations. Say, have you seen my LinkedIn articles about variable data, or seen John Garrett's Lynda tutorial on it?
Of course, it goes without saying, I am available for making custom scripts for your workflow - but also lets's connect on LinkedIn if we are not already.
Thanks for using this script!
See my profile: https://www.linkedin.com/in/vasily-hall-91216618/

**Comment by sfdesigner** [comment]
I actually found out about your script through John's course! I'll definitely connect on LinkedIn and I might be interested in seeing more automation support. My work email is doug@linkedin.com

Thanks, and I'll check out your article!

DougW

Get Outlook for Android<https://aka.ms/ghei36>
